### ISSUE TITLE
dht11_example.py used

### ISSUE THREAD

**Issue by patilomkar865** [szazo/DHT11_Python#12]
pi@raspberrypi:~ $ python dht11.py
Traceback (most recent call last):
  File "dht11.py", line 2, in <module>
    import dht11
  File "/home/pi/dht11.py", line 12, in <module>
    instance = dht11.DHT11(pin=14)
AttributeError: 'module' object has no attribute 'DHT11'

**Comment by jacobfister** [comment]
I have the same issue. Couldn't figure out why.

**Comment by mikitachab** [comment]
please try to change name of a script file to something different from library name you want to use.

**Comment by Oosl** [comment]
> please try to change name of a script file to something different from library name you want to use.

Thanks! it works.
